# script to automatically generate the website for Pash
# the generated website data files are pushed in gh-pages branch
name: Pages

on:
  push:
    branches:
      - main
  schedule:
    # At the end of every day
    - cron: "0 0 * * *"
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - name: Building Github Pages
        run: |
          sudo apt-get update -y
          sudo apt-get install nodejs pandoc git -y
          bash web/utils/make.sh
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
